---
name: unit-test
run-name: Run Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - 3.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.4
      - name: Load cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-$${{ hashFiles('**/poetry.lock') }}
      - name: Create cache if not found
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install --no-interaction --no-root
      - name: Install Dependencies
        run: |
          poetry install --no-interaction
      - name: Activate environment
        run: |
          source .venv/bin/activate
      - name: Run pytest
        run: |
          poetry run pytest
